name: future
description: "A simple Financial Application"
publish_to: "none"

version: 0.4.1-dev

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  currency_formatter: ^2.3.0
  easy_localization: ^3.0.8
  envied: ^1.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.2
  form_validator: ^2.1.1
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  google_sign_in: ^7.2.0
  heroicons: ^0.11.0
  hooks_riverpod: ^3.0.3
  intl: ^0.20.2
  package_info_plus: ^9.0.0
  shimmer: ^3.0.0
  supabase_flutter: ^2.10.3

dev_dependencies:
  build_runner: ^2.7.1
  envied_generator: ^1.3.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Italic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-BlackItalic.otf
          style: italic
          weight: 900
